---
name: "Tag Release"

on:
  push:
    tags:
      - "v*"

jobs:
  tag-release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: "Set release name"
        run: |
          export RELEASE_NAME="${{ github.event.repository.name }}-${GITHUB_REF/refs\/tags\//}"
          echo "::set-env name=NAME::$RELEASE_NAME"
        
      - name: "Build"
        if: success()
        run: |
          cd $GITHUB_WORKSPACE
          mkdir plugins
          mv LICENSE plugins/
          mkdir python
          mkdir python/plugins
          mv LICENSE python/plugins/
          mv megascan_link_js/ plugins/
          mv megascan_link_python/ python/plugins/
          zip -r "${{ env.NAME }}.zip" python plugins

      - uses: "marvinpinto/action-automatic-releases@latest"
        if: success()
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: ${{ env.NAME }}.zip
